    # Etapa 1: build
    FROM node:18-alpine AS build
    WORKDIR /app
    COPY package*.json ./
    RUN npm install
    COPY . .
    RUN npm run build

    # Etapa 2: producción
    FROM nginx:alpine
    COPY --from=build /app/dist /usr/share/nginx/html
    USER nginx
    EXPOSE 80